### ISSUE TITLE
扩展flume相关类实现格式化nginx的日志格式

### ISSUE THREAD

**Issue by fenggolang** [qianshangding/fish-flume#1]
在win上编译flume1.6的源码，失败，导致后续不能导入eclipse中扩展Nginx的类，

编译flume编码错误信息如下：
[ERROR] Failed to execute goal on project flume-ng-morphline-solr-sink: Could no
t resolve dependencies for project org.apache.flume.flume-ng-sinks:flume-ng-morp
hline-solr-sink:jar:1.6.0: Failed to collect dependencies at org.kitesdk:kite-mo
rphlines-all:pom:1.0.0 -> org.kitesdk:kite-morphlines-useragent:jar:1.0.0 -> ua_
parser:ua-parser:jar:1.3.0: Failed to read artifact descriptor for ua_parser:ua-
parser:jar:1.3.0: Could not transfer artifact ua_parser:ua-parser:pom:1.3.0 from
/to maven-twttr (http://maven.twttr.com): Connect to maven.twttr.com:80 [maven.t
wttr.com/159.106.121.75] failed: Connection timed out: connect -> [Help 1]

**Comment by qianshangding** [comment]
这是因为连不上http://maven.twttr.com，有两种方法：
1，翻墙
2，连oschina的公共库，具体请看我的博客http://blog.csdn.net/qianshangding0708/article/details/48087911
